#!/bin/bash

notify="$HOME/.config/scripts/volume_notify"
v="pamixer --get-volume"
m="pamixer --get-mute"

if [[ $(exec $v) -gt 0 ]]; then
	pamixer -d 5 &&
		$notify "Volume decreased to $(exec $v)" ||
		$notify "Failed to decrease volume" &&
		pamixer -u
else
	pamixer -m &&
		$notify "Volume is muted"
fi

